on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n shinysls -g shinysls94e6-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n shinysls --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n shinysls --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n shinysls --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: shinysls.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t shinysls.azurecr.io/testakscluster:${{ github.sha }}
        docker push shinysls.azurecr.io/testakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_testakscluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testakscluster4d51 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testakscluster4d51`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testakscluster4d51
        container-registry-url: shinysls.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: testaksclustdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: testakscluster4d51
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          shinysls.azurecr.io/testakscluster:${{ github.sha }}
        imagepullsecrets: |
          testaksclustdockerauth